include:
   - infra.yaml
services:
  web:
    build: .
    ports:
      # container port: app port
      - "8000:5000"
    develop:
      watch:
        - action: sync
          path: .
          target: /code
